### PR TITLE
fix(github): Resolve branch name issue for protected branches

### LINKED ISSUE #1417: Branch name is detected as [object Object] for protected branches in the Github integration
**Describe the bug**:
When working with branches in the Github integration, like saving or loading models the branch name is detected wrongly as [object Object]. This happens because the logic assume a string but is given an object in case of protected branches.

**Expected behaviour**:
Working with branches should just work. Saving models to a protected branch should work.

**Environment**:

- Version: 2.5.0
- Platform: Web App
- OS: macOS 26.2
- Browser: Firefox 147.0b5 (aarch64)

**To Reproduce**:

**Code of Conduct**:

By submitting this issue, you agree to follow our [Code of Conduct](../code_of_conduct.md)
and have read the [contributing guidelines](../contributing.md)

**Any additional context, screenshots, etc**:

Image

### PR DESCRIPTION
**Pull request by eratio08**
**Summary**:

Resolves #1417

Currently it's not possible to perform any api action on protected branches using the Github integration. The branch name is not determined correctly as the logic assumes the `branch` to be a simple string when it's actually an object.

**Description for the changelog**:

Check if the branch parameter is an object to access the `value` field for the branch name, otherwise use the parameter as the `branch` name.

**Declaration**:

- [x] appropriate unit tests have been created / modified
- [ ] functional tests created / modified for changes in functionality (Not sure if this applies, due to the github scope)
- [x] any use of AI has been declared in this pull request

**Other info**:
❌

### CODE REVIEW

File: td.vue/src/views/git/BranchAccess.vue [hunk 1]
```diff
@@ -31,13 +31,12 @@
 
 <script>
 import { mapState } from 'vuex';
-
-import branchActions from '@/store/actions/branch.js';
+import AddBranchModal from '@/components/AddBranchDialog.vue';
+import TdSelectionPage from '@/components/SelectionPage.vue';
 import { getProviderType } from '@/service/provider/providers.js';
+import branchActions from '@/store/actions/branch.js';
```
Comment (eratio08) [inline td.vue/src/views/git/BranchAccess.vue]: Sorry for this, I need to disable biome.
