### PR TITLE
Bug/duplicated diagram overwrites original

### LINKED ISSUE #1296: Duplicated diagram overwrites original
This bug relates to #582 
When a diagram is copied by using the "duplicate" button and editing the duplicate, it will overwrite the original. 

**Expected behaviour**:
The duplicated diagram should not overwrite the original diagram after editing the duplicate.

**Environment**:

- Version: 2.4.1-latest
- Platform: Web App + Desktop 
- OS: Windows + Linux + MacOS
- Browser: Chrome + others

**To Reproduce**:

1. Create a new project
2. Add a diagram called "first"
3. Use the "duplicate" function
4. Try to rename the copy -> Observe the name of both diagram change
5. Save and close
6. Edit Project again and rename the copy again -> Only one diagram will rename
7. Save and close
8. Edit the copied diagram
9. Save and close the diagram
10. Observe the copy has overwritten the original

### PR DESCRIPTION
**Pull request by fparuce**
**Summary**:
Modified the function that duplicates the diagram to create a deep copy of the original diagram, so changes to the copy will no longer affect the original :
- Fixed bug where copy affected the original.
- Added unit test for the diagram duplicate button.

**Description for the changelog**:
bug fix for duplicated diagram overwriting original

**Declaration**:

- [x] appropriate unit tests have been created / modified
- [x] functional tests created / modified for changes in functionality
- [x] any use of AI has been declared in this pull request

**Other info**:
closes #1296

### CODE REVIEW

File: td.vue/src/views/ThreatModelEdit.vue [hunk 1]
```diff
@@ -330,7 +330,7 @@ export default {
             this.$store.dispatch(tmActions.modified);
         },
         onDuplicateDiagramClick(idx) {
-            let newDiagram = this.model.detail.diagrams[idx];
+            let newDiagram = JSON.parse(JSON.stringify(this.model.detail.diagrams[idx]));
```
Comment (jgadsden) [inline td.vue/src/views/ThreatModelEdit.vue:333]: of course, well spotted @fparuce , thank you

**Review by jgadsden — APPROVED** [review]
thank you for the bug-fix @fparuce , and the elegant solution
